import Background from "../../components/Background";
import Nav from "../../components/Nav";
import Footer from "../../components/Footer";

export const metadata = {
  title: "Privacy Policy — LAUDAT",
  description:
    "What data the LAUDAT services process, why, and your rights under the GDPR.",
};

export default function Privacy() {
  return (
    <>
      <Background />
      <Nav />
      <main className="legal">
        <a className="back-link" href="/legal/">
          ← Legal &amp; Policy
        </a>
        <h1>Privacy Policy</h1>
        <p className="legal-meta">Last updated: 13 June 2026</p>

        <p className="lead">
          This policy explains how personal data is handled across the LAUDAT
          website and self-hosted services. The data controller is Mihai Laudat,
          based in Munich, Germany.
        </p>

        <h2>1. What this covers</h2>
        <p>
          This policy applies to <code>laudat.org</code> and its subdomains and
          to the self-hosted applications provided to invited users.
        </p>

        <h2>2. Data processed</h2>
        <ul>
          <li>
            <strong>Account &amp; identity data</strong> — such as a username and
            email address, managed through the single sign-on system, used to
            authenticate you and control access.
          </li>
          <li>
            <strong>Technical logs</strong> — such as IP addresses, timestamps,
            and request metadata generated by reverse proxies, firewalls, and
            applications for security and troubleshooting.
          </li>
          <li>
            <strong>Service content</strong> — files, media, automation state,
            or settings you create within the Services.
          </li>
          <li>
            <strong>Cookies &amp; sessions</strong> — strictly functional cookies
            and tokens needed to keep you signed in. No third-party advertising
            or tracking cookies are used.
          </li>
        </ul>

        <h2>3. Why it is processed &amp; legal basis</h2>
        <p>
          Data is processed to provide and secure the Services, to authenticate
          users, to maintain stability, and to prevent abuse. The legal bases
          under the GDPR are the performance of the user relationship
          (Art. 6(1)(b)) and legitimate interests in operating and securing the
          platform (Art. 6(1)(f)). Where consent is required, it is requested
          separately.
        </p>

        <h2>4. Sharing &amp; processors</h2>
        <p>
          Personal data is not sold or shared for marketing. The platform runs on
          self-managed hardware and on infrastructure providers — including IONOS
          and Hetzner — that act as processors for hosting. Data may be disclosed
          where required by law.
        </p>

        <h2>5. Retention</h2>
        <p>
          Data is kept only as long as needed for the purposes above. Technical
          logs are rotated and deleted on a short cycle; account and content data
          are removed when an account is closed, subject to any legal retention
          requirements.
        </p>

        <h2>6. Your rights</h2>
        <p>
          Under the GDPR you have the right to access, rectify, erase, restrict,
          and port your personal data, and to object to certain processing. You
          also have the right to lodge a complaint with a supervisory authority —
          in Bavaria, the Bayerisches Landesamt für Datenschutzaufsicht (BayLDA).
          To exercise any right, contact the address below.
        </p>

        <h2>7. Security</h2>
        <p>
          Access is protected with single sign-on, network-level access controls
          on a private mesh, reverse proxies, and monitoring. No system is
          perfectly secure, but reasonable technical and organisational measures
          are taken to protect data.
        </p>

        <h2>8. International transfers</h2>
        <p>
          Hosting is located within the EU/EEA where possible. If any processing
          occurs outside the EEA, appropriate safeguards such as Standard
          Contractual Clauses are relied upon.
        </p>

        <h2>9. Contact</h2>
        <p>
          Privacy questions or data-subject requests:{" "}
          <a href="mailto:tckp@duck.com">tckp@duck.com</a>.
        </p>

        <p className="legal-note">
          Provided for the LAUDAT self-hosted services in good faith. This is not
          legal advice.
        </p>
      </main>
      <Footer />
    </>
  );
}
